export type UsListedCompany = {
  ticker: string;
  name: string;
  market_cap: number | null;
  cik: string;
  exchange: string;
  primary_newswire?: string | null;
  updated_at?: string;
  market_cap_updated_at?: string | null;
  newswire_updated_at?: string | null;
  issuer_type?: "DOMESTIC" | "FOREIGN" | null;
  is_unlimited_shelf?: boolean;
  total_registered_offering_capacity?: number | null;
  registered_capacity_updated_at?: string | null;
  shares_outstanding?: number | null;
  shares_outstanding_as_of?: string | null;
  shares_outstanding_class?: string | null;
  share_class?: "CLASS_A" | "CLASS_B" | "CLASS_C" | "ADR" | "COMMON";
  is_active?: boolean;
  previous_tickers?: string[];
};

export type UsListedCompanyRow = {
  ticker: string;
  name: string;
  market_cap: number | null;
  cik: string;
  exchange: string;
  primary_newswire: string | null;
  updated_at: string;
  market_cap_updated_at: string | null;
  newswire_updated_at: string | null;
  issuer_type: "DOMESTIC" | "FOREIGN" | null;
  is_unlimited_shelf: boolean;
  total_registered_offering_capacity: number | null;
  registered_capacity_updated_at: string | null;
  shares_outstanding: number | null;
  shares_outstanding_as_of: string | null;
  shares_outstanding_class: string | null;
  share_class?: "CLASS_A" | "CLASS_B" | "CLASS_C" | "ADR" | "COMMON" | null;
  is_active?: boolean;
  previous_tickers?: string[];
};
